### ISSUE TITLE
Loading SQL Queries is slow

### ISSUE THREAD

**Issue by Real-Gecko** [kolofordjango/kolo#18]
I've noticed that if I have request with a lot of queries and click `SQL Queries` in Kolo it takes some significant time to get the data displayed and CPU fans get crazy as `code` process starts to use 100% of it.
![image](https://user-images.githubusercontent.com/2231969/163544484-61c3580c-9fcd-495c-b5eb-ea815b78be0c.png)
![image](https://user-images.githubusercontent.com/2231969/163544620-4116109d-e159-427e-836c-1f9f6f452b7b.png)
I guess that's because all data is stored in a single db table as JSON. So I assume when data about request is loaded from db it has to be parsed etc.
Maybe it makes sense to split data into different tables?
The resulting JSON seems to have clear structure which can be divided to multiple tables and queued on demand:
![image](https://user-images.githubusercontent.com/2231969/163545519-2d14c59b-c695-4d51-8041-6abefe4fa445.png)

**Comment by wilhelmklopp** [comment]
👋 Thanks for reporting this, definitely something I need to look into. How long would you say it takes at the moment to open the SQL query document? Is it more than 5 seconds? 

And just to confirm: Does it take a long time to open only the first time you open the SQL queries (for a given trace), or every time?


I have a feeling that the slowdown actually comes from the SQL query formatting library we're using: https://www.npmjs.com/package/sql-formatter – I've noticed that being slow in the past 👀 

I don't think it's to do with the database structure since by the time you can see the trace show up in VSCode at all (like in your first screenshot), all data is actually already loaded from the database and parsed.

**Comment by Real-Gecko** [comment]
Depending on number of queries it can take more than 5 seconds. And it happens every time whenever I click `SQL queries` for particular request.
